// frontend/app/components/contents/ViewNews.vue
<script setup lang="ts">
  import type { CraftPageNews } from '~/types/base'

  const props = defineProps<CraftPageNews>()
</script>

<template>
  <div>
    <h1>{{ props.translatablePlainText }}</h1>
    <RichText v-if="props.richText" :text="props.richText" />
    <CraftArea v-if="props.contentBuilder" :content="props.contentBuilder" />

    <h2>Related News</h2>
    <RelatedNews />
  </div>
</template>

// frontend/src/components/content/ViewNews.tsx
import type { CraftPageNews } from '../../types/base'
import RichText from '../RichText'
import { CraftArea } from '@query-api/react'

export default function News(props: CraftPageNews) {
  return (
    <div>
      <h1>{props.translatablePlainText}</h1>
      {props.richText && <RichText text={props.richText} />}
      <CraftArea content={props.contentBuilder} />
    </div>
  )
}
