// frontend/src/components/content/ViewHome.tsx
import { CraftArea } from '@query-api/next'
import { CraftPageHome } from '@/types/base'
import RichText from '@/components/RichText'

export default function Home(props: CraftPageHome) {
  return (
    <>
      <h1>{props.translatablePlainText}</h1>
      {props.richText && <RichText text={props.richText} />}
      <CraftArea content={props.contentBuilder} />
    </>
  )
}

// frontend/app/components/content/ViewHome.vue
<script setup lang="ts">
import type { CraftPageHome } from '~/types/base'

const props = defineProps<CraftPageHome>()
</script>

<template>
  <div>
    <h1>{{ props.translatablePlainText }}</h1>
    <RichText v-if="props.richText" :text="props.richText" />
    <CraftArea v-if="props.contentBuilder" :content="props.contentBuilder" />
  </div>
</template>
